export { UserInterface,UserSignupInterface,UserEmailVerifyInterface,UserLoginInterface } from './user.interface'
export { PostInterface,GetAllPostInterface,UpdatePostInterface } from './post.interface'
export { CommentInterface, UpdateCommentInterface } from './comment.interface'
export { ReplyInstance } from './reply.interface'
export { LikeInterface } from './like.interface'