export { UserInterface,UserSignupInterface,UserEmailVerifyInterface,UserLoginInterface } from './user.interface'
export { PostInterface,GetAllPostInterface } from './post.interface'
export { CommentInstance } from './comment.interface'
export { ReplyInstance } from './reply.interface'
export { LikeInstance } from './like.interface'